import neutral from '../assets/lumi/neutral.webp';
import happy from '../assets/lumi/happy.webp';
import excited from '../assets/lumi/excited.webp';
import focused from '../assets/lumi/focused.webp';
import thinking from '../assets/lumi/thinking.webp';
import concerned from '../assets/lumi/concerned.webp';
import encouraging from '../assets/lumi/encouraging.webp';
import celebrating from '../assets/lumi/celebrating.webp';
import sleeping from '../assets/lumi/sleeping.webp';
import calm from '../assets/lumi/calm.webp';
import neutralBadge from '../assets/lumi/badge/neutral.webp';
import happyBadge from '../assets/lumi/badge/happy.webp';
import excitedBadge from '../assets/lumi/badge/excited.webp';
import focusedBadge from '../assets/lumi/badge/focused.webp';
import thinkingBadge from '../assets/lumi/badge/thinking.webp';
import concernedBadge from '../assets/lumi/badge/concerned.webp';
import encouragingBadge from '../assets/lumi/badge/encouraging.webp';
import celebratingBadge from '../assets/lumi/badge/celebrating.webp';
import sleepingBadge from '../assets/lumi/badge/sleeping.webp';
import calmBadge from '../assets/lumi/badge/calm.webp';

/**
 * Lumi's expression set — one pre-rendered artwork per state, never redrawn in
 * CSS/SVG. Generated by scripts/normalize-lumi-assets.py from
 * design/lumi/source/: every full image shares the same head size, head centre
 * and baseline on a 512px canvas, so swapping expressions never makes Lumi
 * jump or change size.
 */
export type LumiExpression =
  | 'neutral'
  | 'happy'
  | 'excited'
  | 'focused'
  | 'thinking'
  | 'concerned'
  | 'encouraging'
  | 'celebrating'
  | 'sleeping'
  | 'calm';

export const LUMI_EXPRESSION_ASSET: Record<LumiExpression, string> = {
  neutral,
  happy,
  excited,
  focused,
  thinking,
  concerned,
  encouraging,
  celebrating,
  sleeping,
  calm,
};

/** Head-crop variants for small surfaces (toasts, dialogs) where the full body is unreadable. */
export const LUMI_BADGE_ASSET: Record<LumiExpression, string> = {
  neutral: neutralBadge,
  happy: happyBadge,
  excited: excitedBadge,
  focused: focusedBadge,
  thinking: thinkingBadge,
  concerned: concernedBadge,
  encouraging: encouragingBadge,
  celebrating: celebratingBadge,
  sleeping: sleepingBadge,
  calm: calmBadge,
};

let preloaded = false;

/**
 * Warms the image cache so the first expression swap cross-fades instead of
 * flashing empty. Runs when the browser is idle so it never competes with the
 * initial page load.
 */
export function preloadLumiAssets() {
  if (preloaded || typeof Image === 'undefined') return;
  preloaded = true;
  const load = () => {
    for (const src of Object.values(LUMI_EXPRESSION_ASSET)) {
      const image = new Image();
      image.src = src;
    }
  };
  if (typeof window.requestIdleCallback === 'function') window.requestIdleCallback(load, { timeout: 4000 });
  else setTimeout(load, 2000);
}
