// Generated by scripts/normalize-lumi-assets.py — do not edit by hand.
import type { LumiExpression } from './lumi-assets';

/** One open eye, in the 512px normalized art canvas. `skin` is the face colour around it (for eyelids). */
export interface LumiEye { cx: number; cy: number; rx: number; ry: number; skin: string; }

/** Neck (512px canvas): the head turns around (pivotX, pivotY); pivotY is also the chin line the art bends across. */
export interface LumiHead { pivotX: number; pivotY: number; }

/** Standing-pose legs and arms (512px canvas) the walk cycle bends. */
export interface LumiWalk { hipY: number; soleY: number; splitX: number; armLeftX: number; armRightX: number; armTopY: number; armBottomY: number; }

export interface LumiRig { eyes: readonly LumiEye[]; blink: boolean; head?: LumiHead; walk?: LumiWalk; }

export const LUMI_RIG: Partial<Record<LumiExpression, LumiRig>> = {
  calm: { blink: false, eyes: [], head: { pivotX: 250.5, pivotY: 356 } },
  concerned: { blink: true, eyes: [{ cx: 217.5, cy: 306.0, rx: 17.5, ry: 20.5, skin: '#fce8c4' }, { cx: 307.0, cy: 297.6, rx: 15.5, ry: 18.9, skin: '#fce8c3' }], head: { pivotX: 247.5, pivotY: 350 } },
  encouraging: { blink: false, eyes: [], head: { pivotX: 271.5, pivotY: 344 } },
  focused: { blink: false, eyes: [{ cx: 205.0, cy: 355.8, rx: 14.5, ry: 17.7, skin: '#fbdfb6' }, { cx: 291.0, cy: 364.2, rx: 17.5, ry: 21.3, skin: '#fce9be' }] },
  happy: { blink: false, eyes: [], head: { pivotX: 249.0, pivotY: 362 } },
  neutral: { blink: true, eyes: [{ cx: 210.0, cy: 296.6, rx: 15.5, ry: 18.9, skin: '#fce7c1' }, { cx: 293.5, cy: 293.6, rx: 15.5, ry: 18.9, skin: '#fdf1cd' }], head: { pivotX: 254.5, pivotY: 359 }, walk: { hipY: 426, soleY: 466, splitX: 254.5, armLeftX: 205, armRightX: 306, armTopY: 362, armBottomY: 420 } },
  thinking: { blink: true, eyes: [{ cx: 225.5, cy: 292.5, rx: 18.0, ry: 22.0, skin: '#fcecc5' }, { cx: 315.0, cy: 271.2, rx: 15.0, ry: 18.3, skin: '#fce6bb' }], head: { pivotX: 246.5, pivotY: 352 } },
};
